{
  "slurmVersion": 1,
  "validationOutputFilters": {
    "prefixFilters": [ ],
    "bgpsecFilters": [ ]
  },
  "locallyAddedAssertions": {
    "prefixAssertions": [
      {
        "asn": 1234,
        "prefix": "12.34.56.0/24",
        "comment": "N/A"
      },
      {
        "asn": 1234,
        "prefix": "12.34.56.0/24",
        "comment": "N/A"
      }
    ],
    "bgpsecAssertions": [
      {
        "asn": 1234,
        "SKI": "AAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "routerPublicKey": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "comment": "N/A"
      },
      {
        "asn": 1234,
        "SKI": "AAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "routerPublicKey": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "comment": "N/A"
      }
    ]
  }
}
