post_install_script = '''
#!/bin/bash -e
#RPM_SYSTEMD_MACROS#

if [ $EUID -ne 0 ]; then
    echo >&2 "ERROR: Routinator postinst script must be run as root"
    exit 1
fi

if [ $1 -eq 1 ] ; then
    # Initial installation
    R_USER=routinator
    R_GROUP=${R_USER}
    R_HOME_DIR=/var/lib/routinator
    R_HOME_DIR_PERMS=700

    # https://github.com/NLnetLabs/routinator/issues/774
    if ! id ${R_USER} > /dev/null 2>&1; then
        # According to the CentOS 7 useradd man page:
        # --user-group causes a group by the same name as the user to be created
        # --create-home should force creation of a home dir even for a system account.
        useradd --home-dir ${R_HOME_DIR} --system --create-home --user-group ${R_USER}
    fi

    # Ensure that the home directory has the correct ownership
    chown -R ${R_USER}:${R_GROUP} ${R_HOME_DIR}

    # Ensure that the home directory has the correct permissions
    chmod ${R_HOME_DIR_PERMS} ${R_HOME_DIR}

    # Run commands equivalent to what the RPM systemd macros would do
    systemd_post routinator.service
    systemd_triggers

    # Force the new service to be activated immediately post-install. This goes against Fedora policy as Fedora says
    # the distribution and system operator decide which services should be activated automatically by way of systemd
    # preset files. E.g. the `systemd.preset` man page says:
    #
    #   It is not recommended to ship preset files within the respective software packages implementing the units, but
    #   rather centralize them in a distribution or spin default policy, which can be amended by administrator policy,
    #   see below.
    #
    #   If no preset files exist, preset operations will enable all units that are installed by default. If this is not
    #   desired and all units shall rather be disabled, it is necessary to ship a preset file with a single, catchall
    #   "disable *" line. (See example 1, below.)
    #
    #   From: https://www.freedesktop.org/software/systemd/man/systemd.preset.html#Description
    #
    # Fedora 36 for example has such a "catchall" "disable *" preset policy.
    # See also: https://stackoverflow.com/a/45058741
    systemctl enable --now routinator.service
fi
'''

pre_uninstall_script = '''
#!/bin/bash -e
#RPM_SYSTEMD_MACROS#

if [ $1 -eq 0 ] ; then
    # Package removal, not upgrade
    # Run commands equivalent to what the RPM systemd macros would do
    systemd_preun routinator.service
    systemd_triggers
fi
'''

post_uninstall_script = '''
#!/bin/bash -e
#RPM_SYSTEMD_MACROS#

if [ $1 -ge 1 ] ; then
    # Run commands equivalent to what the RPM systemd macros would do
    systemd_postun_with_restart routinator.service
    systemd_triggers
fi
'''
